# Generated by Django 5.0.6 on 2024-07-19 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataLoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curr_quarter', models.CharField(default='Q2', max_length=100)),
                ('current_year', models.CharField(default='2021', max_length=100)),
                ('paid_case', models.CharField(default='paid', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('excel_output', models.FileField(blank=True, null=True, upload_to='dataloss/output/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datalosss', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datalosss', to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='UserClientHistoricalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='dataloss/historical_data')),
                ('claims_file', models.FileField(blank=True, null=True, upload_to='dataloss/claims_data')),
                ('reserves_file', models.FileField(blank=True, null=True, upload_to='dataloss/reserves_data')),
                ('upper_bound_update', models.DateField(blank=True, null=True)),
                ('lower_bound_update', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_data', to='api.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
